model:
  language_model:
    tokenizer_name: "facebook/opt-350m"
    llm_name: "facebook/opt-350m"
  type: "resnet50"
  learning_rate: 0.001
  batch_size: 32

data:
  train_path: "../data/pre_1"
  val_path: "../data/pre_1"
  test_path: "../data/pre_1"

  train_batch_size: 4
  train_num_workers: 1

  val_batch_size: 4 
  val_num_workers: 1
  
training:
  num_epochs: 4
  lr: 0.0001
  pre_max_CIDEr: 0

experiment:
  name: "baseline"
  seed: 42
