model:
  language_model:
    tokenizer_name: "meta-llama/Meta-Llama-3.1-8B"
    llm_name: "meta-llama/Meta-Llama-3.1-8B"
  type: "resnet50"
  learning_rate: 0.001
  batch_size: 32

data:
  train_path: "../data/pre_1"
  val_path: "/data/val"

experiment:
  name: "baseline"
  seed: 42
